---
index:
  analysis:
    analyzer:
      talk_analyzer:
        filter:
          - icu_normalizer
          - icu_folding
          - lowercase
          - shingled
        tokenizer: icu_tokenizer
    filter:
      shingled:
        type: shingle
        min_shingle_size: 2
        max_shingle_size: 3

